ALTER TABLE "user_preferences"
ADD COLUMN "tts_language" TEXT NOT NULL DEFAULT 'es-ES',
ADD COLUMN "tts_rate" DOUBLE PRECISION NOT NULL DEFAULT 0.9,
ADD COLUMN "tts_volume" DOUBLE PRECISION NOT NULL DEFAULT 1.0;